language: python

python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
      - graphviz

install:
  - pip install -U pip setuptools
  - pip install .
  - pip install -r requirements.txt

script:
  - cd test/
  - python pydot_unittest.py

# after_success:
#   - coveralls
